---

- name: Loading required modules
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: add kubernetes.conf file to sysctl.d
  file:
    path: "/etc/sysctl.d/kubernetes.conf"
    state: "touch"

- name: Config sysctl
  blockinfile:
    path: "/etc/sysctl.d/kubernetes.conf"
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Reload parameters
  command: sudo sysctl --system
...
