---

- name: kubeadm config images pull
  ansible.builtin.command: 
    cmd: kubeadm config images pull
  register: pull_results

- name: kubeadm init
  ansible.builtin.shell: kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket unix:///run/containerd/containerd.sock --upload-certs  --control-plane-endpoint=master.jlinux.ir --apiserver-advertise-address=188.121.99.99
  register: init_output
  args:
    chdir: $HOME
  when: "'master.jlinux.ir' in inventory_hostname"

- name: Set up kubectl for the current user
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory
    mode: 0755
  when: "'master.jlinux.ir' in inventory_hostname"

- ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: 1000
    group: 1000
  when: "'master.jlinux.ir' in inventory_hostname"

- name: Install Calico pod network
  ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/tigera-operator.yaml
  when: "'master.jlinux.ir' in inventory_hostname"

- ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/custom-resources.yaml
  args:
    chdir: $HOME
  when: "'master.jlinux.ir' in inventory_hostname"

- name: Get the token for join worker to master
  ansible.builtin.shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command
  when: "'master.jlinux.ir' in inventory_hostname"

- ansible.builtin.debug:
    msg: "{{ kubernetes_join_command.stdout }}"
  when: "'master.jlinux.ir' in inventory_hostname"

- name: Copy join command to local file.
  ansible.builtin.copy:
    content: "{{ kubernetes_join_command.stdout_lines[0] }}"
    dest: "/tmp/kubernetes_join_command"
    mode: "0777"
  when: "'master.jlinux.ir' in inventory_hostname"
- ansible.builtin.fetch:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
  when: "'master.jlinux.ir' in inventory_hostname"