---

- name: touch /etc/modules-load.d/containerd.conf
  ansible.builtin.file:
    path: "/etc/modules-load.d/containerd.conf"
    state: "touch"

- name: Configure persistent loading of modules
  ansible.builtin.blockinfile:
    path: "/etc/modules-load.d/containerd.conf"
    block: |
      overlay
      br_netfilter

- name: Load at runtime
  ansible.builtin.shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Reload configs
  command: sudo sysctl --system

- name: Install required packages
  ansible.builtin.apt:
    name: 
      - curl
      - gnupg
      - gpg
      - software-properties-common
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: true

- name: Add Docker repo
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Print architecture variables
  ansible.builtin.debug:
    msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

- name: Add the repository to Apt sources
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: Update and upgrade all packages to the latest version
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install containerd
  ansible.builtin.apt:
    name:
      - containerd.io
    state: present

- name: Configure containerd
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: 0755

- ansible.builtin.shell: |
    containerd config default | tee /etc/containerd/config.toml

- lineinfile:
    insertafter: '.*\[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options\]$'
    line: '            SystemdCgroup = true'
    state: present
    path: /etc/containerd/config.toml

- ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    state: absent
    line: '            SystemdCgroup = false'

- ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: yes